### ISSUE TITLE
How can I play the demo?

### ISSUE THREAD

**Issue by June-Jo** [cxy1997/Robotiq-UR5#3]
Thanks for your good work in advance.

I want to play the demo, so I try to run environment.py file.
But I faced a error below.

`Traceback (most recent call last):
  File "/home/june/venv/BinPickingDataCollector/Robotiq-UR5/environment.py", line 267, in <module>
    angles, state, images = env.reset(0)
  File "/home/june/venv/BinPickingDataCollector/Robotiq-UR5/environment.py", line 102, in reset
    return (remapped_pos,) + self.get_state() 
  File "/home/june/venv/BinPickingDataCollector/Robotiq-UR5/environment.py", line 175, in get_state
    image_1 = copy.deepcopy(self.sim.render(width = 960, height = 720, camera_name = 'workbench_camera'))
  File "mujoco_py/mjsim.pyx", line 149, in mujoco_py.cymj.MjSim.render
  File "mujoco_py/mjsim.pyx", line 151, in mujoco_py.cymj.MjSim.render
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL`

If I solve this problem, can I play the demo?

**Comment by June-Jo** [comment]
It's done under Mujoco 200. Thx!
